@startuml
title Analysis Class Diagram - UC023 RemoveFood

class "RemoveFoodUI" as UI <<boundary>> {
  + Interact() : void
  + Return Data() : void
}
class "RemoveFoodController" as Controller <<control>> {
  + Process Request() : void
}
class "RemoveFoodDB" as Entity <<entity>> {
  + Query/Update DB() : void
}

Controller -- UI
Controller -- Entity
@enduml
