@startuml
title Communication Diagram - UC024 AutoDeductFood

allow_mixing
actor "User" as Actor
boundary "AutoDeductFoodUI" as UI
control "AutoDeductFoodController" as Controller
entity "AutoDeductFoodDB" as Entity

Actor -right-> UI : 1: Interact
UI -right-> Controller : 2: process()
Controller -down-> Entity : 3: dbAction()
Controller -up-> UI : 4: returnData
@enduml
