@startuml
title Communication Diagram - UC023 RemoveFood

allow_mixing
actor "User" as Actor
boundary "RemoveFoodUI" as UI
control "RemoveFoodController" as Controller
entity "RemoveFoodDB" as Entity

Actor -right-> UI : 1: Interact
UI -right-> Controller : 2: process()
Controller -down-> Entity : 3: dbAction()
Controller -up-> UI : 4: returnData
@enduml
