@startuml
title Analysis Class Diagram - UC020 ViewPantry

class "ViewPantryUI" as UI <<boundary>> {
  + Interact() : void
  + Return Data() : void
}
class "ViewPantryController" as Controller <<control>> {
  + Process Request() : void
}
class "ViewPantryDB" as Entity <<entity>> {
  + Query/Update DB() : void
}

Controller -- UI
Controller -- Entity
@enduml
