@startuml
title Sequence Diagram - UC021 AddFoodManually

actor "User" as Actor
boundary "AddFoodManuallyUI" as UI
control "AddFoodManuallyController" as Controller
entity "AddFoodManuallyDB" as Entity

Actor -> UI : 1. Interact
activate UI
UI -> Controller : 2. handleRequest()
activate Controller
Controller -> Entity : 3. executeDbAction()
activate Entity
Entity --> Controller : 4. resultData
deactivate Entity
Controller --> UI : 5. status/data
deactivate Controller
UI --> Actor : 6. showResult()
deactivate UI
@enduml
