@startuml
title Communication Diagram - UC021 AddFoodManually

allow_mixing
actor "User" as Actor
boundary "AddFoodManuallyUI" as UI
control "AddFoodManuallyController" as Controller
entity "AddFoodManuallyDB" as Entity

Actor -right-> UI : 1: Interact
UI -right-> Controller : 2: process()
Controller -down-> Entity : 3: dbAction()
Controller -up-> UI : 4: returnData
@enduml
