@startuml
title Sequence Diagram - UC019 FinishShopping

actor "User" as Actor
boundary "FinishShoppingUI" as UI
control "FinishShoppingController" as Controller
entity "FinishShoppingDB" as Entity

Actor -> UI : 1. Interact
activate UI
UI -> Controller : 2. handleRequest()
activate Controller
Controller -> Entity : 3. executeDbAction()
activate Entity
Entity --> Controller : 4. resultData
deactivate Entity
Controller --> UI : 5. status/data
deactivate Controller
UI --> Actor : 6. showResult()
deactivate UI
@enduml
