@startuml
title Analysis Class Diagram - UC017 AddItemToList

class "ShoppingUI" as UI <<boundary>> {
  + inputItemDetails() : void
  + displayUpdate() : void
}
class "ShoppingController" as Controller <<control>> {
  + addItem(listId: String, itemName: String, quantity: Number) : void
}
class "ShoppingDB" as Entity <<entity>> {
  + saveItem(listId: String, itemName: String, quantity: Number) : String
}

Controller -- UI
Controller -- Entity
@enduml
