@startuml
title Sequence Diagram - UC017 AddItemToList

actor "User" as Actor
boundary "AddItemToListUI" as UI
control "AddItemToListController" as Controller
entity "AddItemToListDB" as Entity

Actor -> UI : 1. Interact
activate UI
UI -> Controller : 2. handleRequest()
activate Controller
Controller -> Entity : 3. executeDbAction()
activate Entity
Entity --> Controller : 4. resultData
deactivate Entity
Controller --> UI : 5. status/data
deactivate Controller
UI --> Actor : 6. showResult()
deactivate UI
@enduml
