@startuml
title Analysis Class Diagram - UC027 ManageMeal

class "ManageMealUI" as UI <<boundary>> {
  + Interact() : void
  + Return Data() : void
}
class "ManageMealController" as Controller <<control>> {
  + Process Request() : void
}
class "ManageMealDB" as Entity <<entity>> {
  + Query/Update DB() : void
}

Controller -- UI
Controller -- Entity
@enduml
