@startuml
title Analysis Class Diagram - UC008 CreateFamilyGroup

class "CreateFamilyGroupUI" as UI <<boundary>> {
  + Interact() : void
  + Return Data() : void
}
class "CreateFamilyGroupController" as Controller <<control>> {
  + Process Request() : void
}
class "CreateFamilyGroupDB" as Entity <<entity>> {
  + Query/Update DB() : void
}

Controller -- UI
Controller -- Entity
@enduml
