@startuml
title Analysis Class Diagram - UC013 RemoveMember

class "RemoveMemberUI" as UI <<boundary>> {
  + Interact() : void
  + Return Data() : void
}
class "RemoveMemberController" as Controller <<control>> {
  + Process Request() : void
}
class "RemoveMemberDB" as Entity <<entity>> {
  + Query/Update DB() : void
}

Controller -- UI
Controller -- Entity
@enduml
