@startuml
title Analysis Class Diagram - UC010 GenerateInviteCode

class "GenerateInviteCodeUI" as UI <<boundary>> {
  + Interact() : void
  + Return Data() : void
}
class "GenerateInviteCodeController" as Controller <<control>> {
  + Process Request() : void
}
class "GenerateInviteCodeDB" as Entity <<entity>> {
  + Query/Update DB() : void
}

Controller -- UI
Controller -- Entity
@enduml
