@startuml
title Sequence Diagram - UC013 RemoveMember

actor "User" as Actor
boundary "RemoveMemberUI" as UI
control "RemoveMemberController" as Controller
entity "RemoveMemberDB" as Entity

Actor -> UI : 1. Interact
activate UI
UI -> Controller : 2. handleRequest()
activate Controller
Controller -> Entity : 3. executeDbAction()
activate Entity
Entity --> Controller : 4. resultData
deactivate Entity
Controller --> UI : 5. status/data
deactivate Controller
UI --> Actor : 6. showResult()
deactivate UI
@enduml
