@startuml
title Analysis Class Diagram - UC034 ViewStatistics

class "ViewStatisticsUI" as UI <<boundary>> {
  + Interact() : void
  + Return Data() : void
}
class "ViewStatisticsController" as Controller <<control>> {
  + Process Request() : void
}
class "ViewStatisticsDB" as Entity <<entity>> {
  + Query/Update DB() : void
}

Controller -- UI
Controller -- Entity
@enduml
