@startuml
title Communication Diagram - UC038 ApproveRecipe

allow_mixing
actor "User" as Actor
boundary "ApproveRecipeUI" as UI
control "ApproveRecipeController" as Controller
entity "ApproveRecipeDB" as Entity

Actor -right-> UI : 1: Interact
UI -right-> Controller : 2: process()
Controller -down-> Entity : 3: dbAction()
Controller -up-> UI : 4: returnData
@enduml
